from __future__ import absolute_import

from .bbox_fitting import bbox_fitting
from .bbox_fitting_center import bbox_fitting_center
from .bbox_fitting_center_by_scale import bbox_fitting_center_by_scale
